### ISSUE TITLE
Launch Checklist

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xplsql#1]
In order to launch we should have:

- [x] pl/sql as a submodule in [x-api](https://github.com/exercism/x-api/tree/master/problems)
- [x] at least 10 problems
- [x] a "how to get started" topic in the [help repo](https://github.com/exercism/docs) repo (`app/pages/languages/getting-started-with-plsql.md`)
- [x] one to a handful of people willing to check exercism regularly (daily?) for nitpicks to ensure that the track gets off on the right foot
- [x] toggle `"active"` to `true` in `config.json`

Some tracks have been more successful than others, and I believe the key features of the successful tracks are:

* Each submission receives feedback quickly, preferably within the first 24 hours.
* The nitpicks do not direct users to do specific things, but rather ask questions challenging people to think about different aspects of their solution, or explore new aspects of the language.

For more about contributing to language tracks on exercism, check out the Problem API Contributing guide: https://github.com/exercism/x-api/blob/master/CONTRIBUTING.md

**Comment by chezwicker** [comment]
I'll certainly check regularly for some time now. I've now set the language to active. Hoping for some interest ;-)

**Comment by chezwicker** [comment]
Do I have to submit a solution to each of the problems in order to be able to nitpick?

**Comment by kytrinyx** [comment]
I'll add you as a mentor to the track, that way you don't have to submit solutions yourself.

**Comment by kytrinyx** [comment]
Done!

**Comment by chezwicker** [comment]
Cool, thank you!
